### PR TITLE
FIX: Check Bech32 uppercase address

### LINKED ISSUE #2910: Check Address from Samourai
## Description

None of the available wallets own the provided address.

## Steps to Reproduce

1. Create a wallet on Samourai.
2. Export zpub on Samourai.
3. Import zpub on BlueWallet.
4. Check Address on BlueWallet, scanning the QRCode generated by Samourai.

### zpub

`zpub6s3d92fYtb9txirTeE5eXZ34qe4j3ca2i2EYaxf9ZxrH2X9b6yXdB45u4vxq6YYCEzcmHbakjEEQXPrVKdu4LBDA7cxEGbA4kvyNPfcN2Rz`

zpub

### Samourai address

`BC1QPZYEDTSM8XW2PQ29R6V9PCV2EZYG87QL0Q9NDX`

address

### BlueWallet address check

check

## Possible Fix

Ignore or transform uppercase text.

## Environment

- BlueWallet version: _6.0.7_
- Samourai version: _0.99.96f_
- Wallet type: _Bech32 Imported Watch-only_

### PR DESCRIPTION
**Pull request by jaonoctus**
Fix #2910 

image

### CODE REVIEW

**Review by limpbrains — APPROVED** [review]

**Review by marcosrdz — APPROVED** [review]

File: class/wallets/abstract-hd-electrum-wallet.js [hunk 1]
```diff
@@ -836,11 +836,17 @@ export class AbstractHDElectrumWallet extends AbstractHDWallet {
   }
 
   weOwnAddress(address) {
+    let cleanAddress = address;
+
+    if (this.type === 'HDsegwitBech32') {
```
Comment (Overtorment) [inline class/wallets/abstract-hd-electrum-wallet.js:841]: its better to check for  `this.segwitType === 'p2wpkh'`. to great solution, but its a bit more reliable constant.


a bit similar how its done in `sign/verify` functionality:

```
signMessage(message, address) {
    const wif = this._getWIFbyAddress(address);
    if (wif === null) throw new Error('Invalid address');
    const keyPair = bitcoin.ECPair.fromWIF(wif);
    const privateKey = keyPair.privateKey;
    const options = this.segwitType ? { segwitType: this.segwitType } : undefined;
```

File: class/wallets/abstract-hd-electrum-wallet.js [hunk 2]
```diff
@@ -836,11 +836,17 @@ export class AbstractHDElectrumWallet extends AbstractHDWallet {
...
     for (let c = 0; c < this.next_free_address_index + this.gap_limit; c++) {
-      if (this._getExternalAddressByIndex(c) === address) return true;
+      if (this._getExternalAddressByIndex(c) === cleanAddress) return true;
     }
     for (let c = 0; c < this.next_free_change_address_index + this.gap_limit; c++) {
-      if (this._getInternalAddressByIndex(c) === address) return true;
+      if (this._getInternalAddressByIndex(c) === cleanAddress) return true;
     }
     return false;
   }
```
Comment (Overtorment) [inline class/wallets/abstract-hd-electrum-wallet.js:852]: same change is needed for single-address wallets: `LegacyWallet.weOwnAddress()`

**Review by Overtorment — CHANGES_REQUESTED** [review]
also, missing basic unit tests, for both bech32 HD (BIP84 & aezeed) and bech32 single-address

**Review by limpbrains — APPROVED** [review]
