### PR TITLE
FIX: camera wont scan QR with airgapped HW wallet flow (closes #1764)

### LINKED ISSUE #1764: Cobo Vault; Scan to broadcast transaction is broken
1.) Scan PSBT Barcode to CoboVault
2.) Sign Ttansaction
3.) scan barcode with the signed transaction from CoboVault
The barcode will not be recognized by BlueWallet. I made several attempt on an Android Samsung Smartphone. Reproducible with an iPad tablet. 

Version: 5.5.8 (build 1599752722)

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

File: Navigation.js [hunk 1]
```diff
@@ -312,6 +303,15 @@ const Navigation = () => (
     <RootStack.Screen name="SelectWallet" component={SelectWallet} options={{ headerLeft: null }} />
     <RootStack.Screen name="ReceiveDetails" component={ReceiveDetails} options={ReceiveDetails.navigationOptions} />
     <RootStack.Screen name="LappBrowser" component={LappBrowser} options={LappBrowser.navigationOptions} />
+
+    <RootStack.Screen
```
Comment (Overtorment) [inline Navigation.js:307]: I had to add it otherwise some other error was throwing

**Review by marcosrdz — APPROVED** [review]

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x4cj2zkvnmmqk3qgkdcmh6n7ur

[download apk](http://filestorage.bluewallet.io:1488/1600091464.apk)
