### PR TITLE
FIX: some cases of lnurl-withdraw (closes #2213)

### LINKED ISSUE #2213: Cannot scan lnurl-withdraw QR code from wallet->send/receive->scan
Occurs on both Android and iOS when using the "Scan" button to scan an lnurl-withdraw QR code within a wallet after selecting "Receive" or "Send". 

"Scan" from the homescreen works fine.

cc2b4ccc-c6e1-4ee0-8133-2aa224a84f46

Tested in version 5.6.6.

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

File: screen/lnd/lndCreateInvoice.js [hunk 1]
```diff
@@ -131,6 +131,10 @@ const LNDCreateInvoice = () => {
             },
           });
         }
+      } else {
+        ReactNativeHapticFeedback.trigger('notificationError', { ignoreAndroidSystemSettings: false });
+        alert(loc.wallets.add_ln_wallet_first);
+        goBack();
```
Comment (Overtorment) [inline screen/lnd/lndCreateInvoice.js:137]: not sure if I used correct useFocusEffect+useCallback with `wallet` dep, but it seems to work

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rxuyhfgtdr4d9gcwn1m1bqaf58

[download apk](http://filestorage.bluewallet.io:1488/1607611100.apk)

**Review by limpbrains — APPROVED** [review]

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/duxtjg1gq4arvg55unj335hzag

[download apk](http://filestorage.bluewallet.io:1488/1607631260.apk)
