### PR TITLE
FIX: rare freezes on send screen (closes #1945)

### LINKED ISSUE #1945: Send screen freezes
https://imgur.com/a/kcoMTiU

Send screen freezes with bad connection or vpn. Reproducible by accessing the screen in flight mode.

Possible mitigations:
- view should not be dependent on network connection
- don't allow the view to freeze
- throw an error
- gracefully fallback to not fetch utxo and use sats/b

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/06r1346pvm09jj29d2nkut6epc

[download apk](http://filestorage.bluewallet.io:1488/1601921059.apk)

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dubmpfm7qw4ua1dr0rxm2autww

[download apk](http://filestorage.bluewallet.io:1488/1601935335.apk)

File: models/networkTransactionFees.js [hunk 1]
```diff
@@ -20,20 +20,20 @@ export class NetworkTransactionFee {
...
+    return new Promise(async resolve => {
       try {
         const response = await BlueElectrum.estimateFees();
         if (typeof response === 'object') {
           const networkFee = new NetworkTransactionFee(response.fast, response.medium, response.slow);
           resolve(networkFee);
         } else {
           const networkFee = new NetworkTransactionFee(1, 1, 1);
-          reject(networkFee);
+          resolve(networkFee);
```
Comment (limpbrains) [inline models/networkTransactionFees.js:31]: Omg, it was broken all the time

**Review by limpbrains — APPROVED** [review]
