### PR TITLE
FIX: proper fee estimation for multisig wallets (closes #3811)

### LINKED ISSUE #3811: proper fee estimations for multisig
similar to https://github.com/BlueWallet/BlueWallet/pull/3810 but need to factor in `m` & `n`

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

File: class/wallets/multisig-hd-wallet.js [hunk 1]
```diff
@@ -794,6 +794,17 @@ export class MultisigHDWallet extends AbstractHDElectrumWallet {
...
+    for (const u of utxos) {
+      if (this.isNativeSegwit()) {
+        u.script = u.script || { length: Math.ceil((8 + this.getM() * 73 + this.getN() * 34) / 4) };
+      } else if (this.isWrappedSegwit()) {
+        u.script = u.script || { length: 35 + Math.ceil((8 + this.getM() * 73 + this.getN() * 34) / 4) };
+      } else {
+        u.script = u.script || { length: 9 + this.getM() * 73 + this.getN() * 34 };
+      }
+    }
+
```
Comment (Overtorment) [inline class/wallets/multisig-hd-wallet.js:807]: @junderw can you pls take a look?

**Comment by Overtorment** [comment]
@jaonoctus can you take a look as well pls?

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ejaka4py8b30x23ftpngqn6cwg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8536)

File: class/wallets/multisig-hd-wallet.js (hunk 1 above)
Comment (junderw) [reply class/wallets/multisig-hd-wallet.js:807]: I don't think you should do `u.script || `

Even if an object referring to a utxo contained something called `script` it will not be what you are looking for in regards to segwit, and I doubt it will be what you're looking for in regards to non-segwit too.

Comment (junderw) [reply class/wallets/multisig-hd-wallet.js:807]: Other than that, the lengths to the right of || should be correct (or close enough, erring on the side of being less than a vbyte too large)

Comment (junderw) [reply class/wallets/multisig-hd-wallet.js:807]: I see you're using `u.script ||` for testing.

It might be better to add a `forTest: true` attribute.

in the code: `u.script && u.script.forTesting === true ? u.script : { length: ... }`
in the tests: `{ length: 107, forTesting: true }`

**Comment by jaonoctus** [comment]
When I have multisig outputs, the fee is lower than expected.

## test 01
```
1 input (2/3 multisig)
1 output (segwit native)

electrum fee (1 sat/vByte): 146 sats
bluewallet fee (1 sat/vByte): 149 sats
```

## test 02
```
1 input (2/3 multisig)
1 output (2/3 multisig)

electrum fee (1 sat/vByte): 158 sats
bluewallet fee (1 sat/vByte): 149 sats
```

## test 03
```
2 inputs (2/3 multisig)
1 output (segwit native)

electrum fee (1 sat/vByte): 251 sats
bluewallet fee (1 sat/vByte): 254 sats
```

## test 04
```
2 inputs (2/3 multisig)
1 output (2/3 multisig)

electrum fee (1 sat/vByte): 263 sats
bluewallet fee (1 sat/vByte): 254 sats
```

## test 05
```
2 inputs (2/3 multisig)
2 output (1 segwit native, 1 2/3 multisig)

electrum fee (1 sat/vByte): 300 sats
bluewallet fee (1 sat/vByte): 288 sats
```

**Comment by junderw** [comment]
I have tested using bitcoinjs-lib sizes of actual signed transactions.

See here to reproduce: https://gist.github.com/junderw/6e9610442c154cff408bcf077b3fbdab

Note: BW estimate is consistently over 4 vBytes larger than actual for p2sh. Other than that, segwit (which is easier to estimate) is within 0-1 range.

Results:

```
p2sh-p2ms(14 of 15)
Expected: 1581
Actual: 1574.7
Diff (negative is bad): 6.2999999999999545

p2sh-p2wsh-p2ms(14 of 15)
Expected: 460
Actual: 459.1
Diff (negative is bad): 0.8999999999999773

p2wsh-p2ms(14 of 15)
Expected: 425
Actual: 424.3
Diff (negative is bad): 0.6999999999999886

p2sh-p2ms(14 of 15)
Expected: 1581
Actual: 1574.7
Diff (negative is bad): 6.2999999999999545

p2sh-p2wsh-p2ms(14 of 15)
Expected: 460
Actual: 459
Diff (negative is bad): 1

p2wsh-p2ms(14 of 15)
Expected: 425
Actual: 424.2
Diff (negative is bad): 0.8000000000000114

p2sh-p2ms(14 of 15)
Expected: 1581
Actual: 1574.8
Diff (negative is bad): 6.2000000000000455

p2sh-p2wsh-p2ms(14 of 15)
Expected: 460
Actual: 459.3
Diff (negative is bad): 0.6999999999999886

p2wsh-p2ms(14 of 15)
Expected: 425
Actual: 424.2
Diff (negative is bad): 0.8000000000000114

p2sh-p2ms(14 of 15)
Expected: 1581
Actual: 1574.6
Diff (negative is bad): 6.400000000000091

p2sh-p2wsh-p2ms(14 of 15)
Expected: 460
Actual: 459.4
Diff (negative is bad): 0.6000000000000227

p2wsh-p2ms(14 of 15)
Expected: 425
Actual: 423.9
Diff (negative is bad): 1.1000000000000227

p2sh-p2ms(14 of 15)
Expected: 1581
Actual: 1573.5
Diff (negative is bad): 7.5

p2sh-p2wsh-p2ms(14 of 15)
Expected: 460
Actual: 459.5
Diff (negative is bad): 0.5

p2wsh-p2ms(14 of 15)
Expected: 425
Actual: 424.4
Diff (negative is bad): 0.6000000000000227

p2sh-p2ms(14 of 15)
Expected: 1581
Actual: 1574.2
Diff (negative is bad): 6.7999999999999545

p2sh-p2wsh-p2ms(14 of 15)
Expected: 460
Actual: 459.4
Diff (negative is bad): 0.6000000000000227

p2wsh-p2ms(14 of 15)
Expected: 425
Actual: 424
Diff (negative is bad): 1

p2sh-p2ms(14 of 15)
Expected: 1581
Actual: 1576.4
Diff (negative is bad): 4.599999999999909

p2sh-p2wsh-p2ms(14 of 15)
Expected: 460
Actual: 459.1
Diff (negative is bad): 0.8999999999999773

p2wsh-p2ms(14 of 15)
Expected: 425
Actual: 424
Diff (negative is bad): 1

p2sh-p2ms(14 of 15)
Expected: 1581
Actual: 1574.7
Diff (negative is bad): 6.2999999999999545

p2sh-p2wsh-p2ms(14 of 15)
Expected: 460
Actual: 459.1
Diff (negative is bad): 0.8999999999999773

p2wsh-p2ms(14 of 15)
Expected: 425
Actual: 424.1
Diff (negative is bad): 0.8999999999999773
```

**Review by junderw — APPROVED** [review]

**Review by junderw — CHANGES_REQUESTED** [review]
Actually, running the tests again for 2-of-3, I found that the signature sizes are for low R and low S.

low S is automatically done, but low R is not default, so if we want to stay above, 73 should be bumped to 74.

Please bump all 73 (signature estimate) to 74.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5ed7q0qwramd6c0m8e56g32th8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8558)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z1jbmduduvd2gbkamvc19p4vew?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8559)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Review by limpbrains — APPROVED** [review]

**Review by junderw — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Comment by Overtorment** [comment]
merged. thanks all
