### PR TITLE
FIX: import Casa multisig wallet descriptor (closes #7395)

### LINKED ISSUE #7395: Wallet Descriptor Import fails with "path is not valid" error
Trying to import a wallet descriptor for a Casa multisig and getting an error that's a bit vague.

Please provide:

Phone Model: Pixel 8 Pro
OS: GrapheneOS
BlueWallet app version 7.0.6
self-test passes? yes

Here's the descriptor with which I'm testing. I'm able to successfully import it into Sparrow.
```
sh(wsh(sortedmulti(3,[35282ae3]Ypub6j9gr7f7uvWfTHdwVwhYRowZH9oqkh9DZz2hdbeKJw7yjQbsfqaruLva2piTZqN7jSKT43LpsnAqHU4vufUGAyGBzD6UJpwTeKiG5JRYUnm/<0;1>/*,[1b373e31/49/0/5]Ypub6iPAfqqinG5VHf2sJ3XfRjFh8BXm4C6x4U3DaPyu4RKocnqzb1peStw8Q624jwXpMZ5G81s7uwq8qLQ8rW55aZ3LvBbr9XVLTYxG78k28PE/<0;1>/*,[0d7bb846/49/0/5]Ypub6hwdyxEzktht47xgyyFY7TFrAzW7XgGbMSqS3QzfosYekG9LibhpohY6LrsjfP55VyU8i7iWS2s2Vs6RkAeze6bSpU3rNHsmESymE8X3J3k/<0;1>/*,[faa45c74/49/0/5]Ypub6iSiDkVrTTEh6eFbkCvohn1FfuhGr1Co9MCCHi6VPTT6crnX9Avq3PnZj7JcqhDTkWoDLEyeWmaPyxDY22b7k652Sg2eMc2g5tU6GDTvSng/<0;1>/*,[0551354e/49/0/5]Ypub6ipvk7JbDUXormRsSxXRf9eTUAVFwcjDfZXWYxRdN6nV7MNnnuD3WZBYjjWnMTncHhKJsnfkUGVYMRgQthZqY2wfHfMaJoVYBBhHT7MACGs/<0;1>/*)))
```

Maybe this is related to #2958 ?

### PR DESCRIPTION
**Pull request by Overtorment**
## Summary by CodeRabbit

- **New Features**
	- Enhanced wallet descriptor import functionality for Casa multisig wallets
	- Improved path handling for wallet derivation

- **Tests**
	- Added test case to verify Casa multisig wallet descriptor import
	- Validated external and internal address generation for multisig wallets

### CODE REVIEW

File: class/wallets/multisig-hd-wallet.ts [hunk 1]
```diff
@@ -629,7 +629,11 @@ export class MultisigHDWallet extends AbstractHDElectrumWallet {
             hexFingerprint = Buffer.from(hexFingerprint, 'hex').toString('hex');
           }
 
-          const path = 'm/' + m[1].split('/').slice(1).join('/').replace(/[h]/g, "'");
+          let path = 'm/' + m[1].split('/').slice(1).join('/').replace(/[h]/g, "'");
+          if (path === 'm/') {
+            // not considered valid by Bip32 lib
```
Comment (Overtorment) [inline class/wallets/multisig-hd-wallet.ts:634]: @junderw i was getting ` Expected BIP32Path, got String "m/"` previously, and overriding it with `m/0` seems to fix the issue (wallet agrees on derived addresses with the same wallet from Sparrow), but i have some doubts  that its correct.
can you pls take a look?

PS. bip32@3.0.1

Comment (junderw) [reply class/wallets/multisig-hd-wallet.ts:634]: m is just “don’t derive anything and return the same HDNode”

m/0 is deriving the first child at index 0.

not sure about how Casa or Sparrow works.

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @junderw] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/junderw

**Review by limpbrains — APPROVED** [review]

**Review by junderw — APPROVED** [review]
I don't understand the original issue well enough to judge if this is correct.

But yes, "m/" is not a valid path.

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

File: class/wallets/multisig-hd-wallet.ts (hunk 1 above)
Comment (macaronish) [reply class/wallets/multisig-hd-wallet.ts:634]: Is any consideration needed with regards to the derivation path length matching that of the other signers in the multisig quorum? For example, using the example from #7395, the path should be set to 'm/0/0/0' instead of just 'm/0'. I say this because I've experienced coldcard throwing a fit when given a PSBT where the derivation path lengths don't match across all signers.
