### PR TITLE
fixed failing import

### LINKED ISSUE #4641: bad master fingerprint from coldcard - 00000000
## Are you reporting a bug?

* M1 Macbook Air 2020 macOS Monterey 12.3.1 (21E258)
* Version 6.2.18 (701)
* OK
* userId:6C2C2A7D-E918-567D-A9D1-2687D42717C5

Coldcard firmware: 4.1.3

When importing electrum wallet json file from coldcard I get an invalid master fingerprint. importing the same json file to electrum client does work without any changes.

### PR DESCRIPTION
**Pull request by raytorres280**
fixes #4641  in event that root_fingerprint is a hex value. does reverse of what Number().toString() does by using parseInt() with radix.

### CODE REVIEW

File: class/wallets/abstract-wallet.ts [hunk 1]
```diff
@@ -244,6 +244,8 @@ export class AbstractWallet {
           masterFingerprint = Number(parsedSecret.keystore.ckcc_xfp);
         } else if (parsedSecret.keystore.root_fingerprint) {
           masterFingerprint = Number(parsedSecret.keystore.root_fingerprint);
```
Comment (raytorres280) [inline class/wallets/abstract-wallet.ts:246]: Should this ever typecast into a number successfully? I know skeleton-electrum.txt has an int for it as an example but I know on latest COLDCARD firmware this always is a hex value after electrum writes to the file.

Is skeleton-electrum.txt a real example?

**Comment by raytorres280** [comment]
I just see warnings on the circleci build. Those lint warnings are causing the failures?

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

File: .gitignore [hunk 2]
```diff
@@ -71,4 +71,7 @@ artifacts/
 
 *.mx
 *.realm
-*.realm.lock
\ No newline at end of file
+*.realm.lock
+
+# Jest
+coverage/
```
Comment (Overtorment) [inline .gitignore:77]: unnecessary change, we dont run coverage reports

File: class/wallets/abstract-wallet.ts [hunk 3]
```diff
@@ -418,4 +419,12 @@ export class AbstractWallet {
   isSegwit() {
     return false;
   }
+
+  getMasterFingerprintFromHex(hexValue: string): number {
+    if (hexValue.length < 8) throw new Error('invalid fingerprint hex');
```
Comment (Overtorment) [inline class/wallets/abstract-wallet.ts:424]: 7 chars hex is still valid, you just need to add leading "0"

File: tests/unit/watch-only-wallet.test.js [hunk 4]
```diff
@@ -185,7 +185,7 @@ describe('Watch only wallet', () => {
     );
   });
 
-  it('can import Electrum compatible backup wallet, and create a tx with master fingerprint', async () => {
+  it('can import Electrum compatible backup wallet, and generate a master fingeprint from a fingerprint hex', async () => {
```
Comment (Overtorment) [inline tests/unit/watch-only-wallet.test.js:188]: unnecessary change

File: tests/unit/watch-only-wallet.test.js [hunk 5]
```diff
@@ -227,6 +227,21 @@ describe('Watch only wallet', () => {
     );
   });
 
+  it('can import Electrum compatible backup wallet, and create a tx with master fingerprint hex', async () => {
```
Comment (Overtorment) [inline tests/unit/watch-only-wallet.test.js:230]: nice

File: class/wallets/abstract-wallet.ts (hunk 1 above)
Comment (Overtorment) [reply class/wallets/abstract-wallet.ts:246]: yeah its real, i got it from some old coldcard i think...

**Review by Overtorment — CHANGES_REQUESTED** [review]
mostly lgtm, needs some changes

**Comment by Overtorment** [comment]
also, circleci started throwing false negatives recently, dont mind it. all test runs are duplicated in `Tests / test (pull_request)`

File: .gitignore (hunk 2 above)
Comment (raytorres280) [reply .gitignore]: that was probably my vs code ext sorry. fixed

File: class/wallets/abstract-wallet.ts (hunk 3 above)
Comment (raytorres280) [reply class/wallets/abstract-wallet.ts:424]: Added some more tests regarding this new info.

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by raytorres280** [comment]
first open source PR 😬 
giphy
