### PR TITLE
FIX: Make BBQR work with multisig

### LINKED ISSUE #8253: Make BBQR work with multisig
Attaching wallet export from Coldcard Q, in BBQR format. 
If you import it through regular wallet-import flow (add wallet->import->scan) app will offer you choice of 3 wallets (legacy, wrapped segwit, native segwit iirc). However, this payload also contains data for multisig cosigners.

So, if you go to add wallet->multisig->start-> press "import" on vault key -> scan -> scan this payload -> correct multisig cosigner data should be added for this vault key.

Makes sense to first test how this flow works with other BLuewallet app: create vault key ->  press "share" -> provided QR code should be importable as vault key

Image
Image
Image
Image
Image
Image
Image

### PR DESCRIPTION
**Pull request by ojokne**
Closes #8253

### CODE REVIEW

File: screen/wallets/addMultisigStep2.tsx [hunk 1]
```diff
@@ -351,8 +351,38 @@ const WalletsAddMultisigStep2 = () => {
           retData = retData.pop();
           returnedData = JSON.stringify(retData);
         }
+
+        // Detect Coldcard  export
```
Comment (Overtorment) [inline screen/wallets/addMultisigStep2.tsx]: ColdcardQ

we need a unit test for this btw, in `tests/unit/multisig-hd-wallet.test.js`

Comment (ojokne) [reply screen/wallets/addMultisigStep2.tsx]: Thanks, will add it

Comment (ojokne) [reply screen/wallets/addMultisigStep2.tsx]: > ColdcardQ
> 
> we need a unit test for this btw, in `tests/unit/multisig-hd-wallet.test.js`

I created a function `extractColdcardQCosigner` that extracts cosigner from coldcardQ data and added unit tests for the it

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

File: util/extractColdcardQCosigner.ts [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+ *
+ * @param {object} data - The parsed JSON object from a ColdcardQ export.
+ * @param {string} format - The multisig wallet format, e.g., p2wsh, p2sh-p2wsh, p2wsh-p2sh, p2sh.
+ * @returns {{ xfp: string, path: string, xpub: string } | undefined} - The extracted cosigner components or undefined if extraction fails.
+ *
+ */
+
+import { MultisigHDWallet } from '../class';
+
+export function extractColdcardQCosigner(data: any, format: string): { xfp: string; path: string; xpub: string } | undefined {
```
Comment (Overtorment) [inline util/extractColdcardQCosigner.ts]: we have a class `class/multisig-cosigner.ts` i would prefer everything cosigner related to be there. 
and a unit test for it as well, no need to add new files

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

File: tests/unit/multisig-hd-wallet.test.js [hunk 3]
```diff
@@ -2127,6 +2127,53 @@ describe('multisig-cosigner', () => {
     assert.strictEqual(cosigner.getFp(), '01EBDA7D');
   });
 
+  it('can parse coldcardQ json', () => {
+    const coldcardQjson = require('./fixtures/coldcardQ.json');
+
+    let data = MultisigCosigner.extractColdcardQCosigner(coldcardQjson, MultisigHDWallet.FORMAT_P2SH_P2WSH);
```
Comment (Overtorment) [inline tests/unit/multisig-hd-wallet.test.js]: its a weir api. we already have a bunch of detecting code in constructor.
use constructor

**Review by Overtorment — CHANGES_REQUESTED** [review]
functionally, it worked

File: tests/unit/multisig-hd-wallet.test.js (hunk 3 above)
Comment (Overtorment) [reply tests/unit/multisig-hd-wallet.test.js]: constructor is used a bit further down in the code

Comment (Overtorment) [reply tests/unit/multisig-hd-wallet.test.js]: see example how we parse into multiple cosigners:


`assert.strictEqual(cosigner.howManyCosignersWeHave(), 3);`

**Comment by Overtorment** [comment]
nevermind, fixed it myself

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Review by limpbrains — APPROVED** [review]
