### PR TITLE
FIX: better support cosigning with Electrum desktop (closes #2401)

### LINKED ISSUE #2401: Co-Signing 2of2 Native Segwit Transactions from Electrum don't work!
Steps to reproduce:

Electrum (4.0.9):
Create a TX based on Seed 1 and Zpub 2
Show QR-Code

Bluewallet (6.0.1):
Vault based on Seed 2 and Zpub 1
Click on Send --> Sign a transaction
Scan QR-Code
TX is shown with Vault key 1 having a green check mark.
Vault key 2 is having a grey check mark.
Confirm button is grayed out.

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by Overtorment** [comment]
@junderw could you please take a look?

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bmcdxg7t1uxd5qvjxwyubbvjk8

[download apk](http://filestorage.bluewallet.io:1488/1609880496.apk)

File: class/wallets/multisig-hd-wallet.js [hunk 1]
```diff
@@ -991,14 +991,48 @@ export class MultisigHDWallet extends AbstractHDElectrumWallet {
    */
   cosignPsbt(psbt) {
     for (let cc = 0; cc < psbt.inputCount; cc++) {
+      let cosignerIndex = 0;
       for (const cosigner of this._cosigners) {
```
Comment (junderw) [inline class/wallets/multisig-hd-wallet.js:995]: `for (const [index, element] of a.entries())` is more concise

File: class/wallets/multisig-hd-wallet.js [hunk 2]
```diff
@@ -991,14 +991,48 @@ export class MultisigHDWallet extends AbstractHDElectrumWallet {
...
+              // match it to the one provided in PSBT's input, and if we have a match - we are in luck! we can sign
+              // with this private key.
+              const pubkeyInpsbt = derivation.pubkey.toString('hex');
+              const seed = bip39.mnemonicToSeed(cosigner);
+              const root = HDNode.fromSeed(seed);
+              const splt = derivation.path.split('/');
+              const internal = +splt[splt.length - 2];
+              const index = +splt[splt.length - 1];
+
+              const path = this.getCustomDerivationPathForCosigner(cosignerIndex) + `/${internal ? 1 : 0}/${index}`;
```
Comment (junderw) [inline class/wallets/multisig-hd-wallet.js:1024]: if internal is > 0 you are collapsing all values into 1.

ie. `25/24` at the end of the original path would become `1/24`

Just wondering if this was intentional.

File: class/wallets/multisig-hd-wallet.js [hunk 3]
```diff
@@ -991,14 +991,48 @@ export class MultisigHDWallet extends AbstractHDElectrumWallet {
...
             psbt.signInputHD(cc, hdRoot);
+            successSigningAsHD = true;
           } catch (_) {} // protects agains duplicate cosignings
+
+          if (!successSigningAsHD) {
+            // failed signing as HD. its either duplicate signature OR bitcoinjs-lib could not match provided hdRoot's
+            // fingerprint (or path?) to the ones in psbt, which is the case of stupid Electrum desktop which can
+            // put bullshit paths and fingerprints in created psbt.
+            // lets try to find correct priv key and sign manually.
+            for (const derivation of psbt.data.inputs[cc].bip32Derivation) {
```
Comment (junderw) [inline class/wallets/multisig-hd-wallet.js:1012]: If there is no bip32Derivation, it might be worth it to have a cache of pubkeys from the most recently used addresses + the next 20 or so addresses, then you could just use `inputHasPubkey`

File: class/wallets/multisig-hd-wallet.js [hunk 4]
```diff
@@ -991,14 +991,48 @@ export class MultisigHDWallet extends AbstractHDElectrumWallet {
...
+      let cosignerIndex = 0;
       for (const cosigner of this._cosigners) {
+        cosignerIndex++;
         if (!MultisigHDWallet.isXpubString(cosigner)) {
           // ok this is a mnemonic, lets try to sign
           const seed = bip39.mnemonicToSeed(cosigner);
           const hdRoot = bitcoin.bip32.fromSeed(seed);
+          let successSigningAsHD = false;
           try {
             psbt.signInputHD(cc, hdRoot);
```
Comment (junderw) [inline class/wallets/multisig-hd-wallet.js:1003]: `inputHasHDKey` method would be easier / cleaner.

File: class/wallets/multisig-hd-wallet.js [hunk 5]
```diff
@@ -991,14 +991,48 @@ export class MultisigHDWallet extends AbstractHDElectrumWallet {
...
+              const index = +splt[splt.length - 1];
+
+              const path = this.getCustomDerivationPathForCosigner(cosignerIndex) + `/${internal ? 1 : 0}/${index}`;
+              // ^^^ we assume that counterparty has Zpub for specified derivation path
+              const child = root.derivePath(path);
+              const pubkeyDerivedFromCosigner = child.publicKey.toString('hex');
+              if (pubkeyInpsbt === pubkeyDerivedFromCosigner) {
+                const keyPair = bitcoin.ECPair.fromPrivateKey(child.privateKey);
+                try {
+                  psbt.signInput(cc, keyPair);
```
Comment (junderw) [inline class/wallets/multisig-hd-wallet.js:1031]: if bip32Derivation pubkey equals this, it should not throw.

However, there's the possibility that the pubkey in bip32Derivation is not actually in the script... so maybe adding a `inputHasPubkey` here to double check could remove the try catch.

File: tests/unit/multisig-hd-wallet.test.js [hunk 6]
```diff
@@ -1052,6 +1052,32 @@ describe('multisig-wallet (native segwit)', () => {
...
+    );
+    assert.strictEqual(wallet.calculateHowManySignaturesWeHaveFromPsbt(psbt), 1);
+
+    const { tx } = wallet.cosignPsbt(psbt); // <---------------------------------------------------------
```
Comment (junderw) [inline tests/unit/multisig-hd-wallet.test.js:1073]: weird... I don't see a return statement in the method at all...

What is tx? lol

**Review by junderw — APPROVED** [review]
meh, most of my comments are not deal breakers.

Feel free to ignore them if you wish.

File: class/wallets/multisig-hd-wallet.js (hunk 1 above)
Comment (Overtorment) [reply class/wallets/multisig-hd-wallet.js:995]: nice, I did not know js can do that

File: class/wallets/multisig-hd-wallet.js (hunk 2 above)
Comment (Overtorment) [reply class/wallets/multisig-hd-wallet.js:1024]: from where im from we call it indian code kek. made it by accident really. but afaik no one uses anything but 0 or 1 for internal/external so we are goo

File: class/wallets/multisig-hd-wallet.js (hunk 3 above)
Comment (Overtorment) [reply class/wallets/multisig-hd-wallet.js:1012]: is there such a software that can be a cosigner and NOT include bip32 derivation in psbt?
Ill leave it as an exercise for when we find such use case and some user will actually complain.

File: class/wallets/multisig-hd-wallet.js (hunk 4 above)
Comment (Overtorment) [reply class/wallets/multisig-hd-wallet.js:1003]: fixed, thanks

File: class/wallets/multisig-hd-wallet.js (hunk 5 above)
Comment (Overtorment) [reply class/wallets/multisig-hd-wallet.js:1031]: so is double check or do `inputHasPubkey` instead?
i mean, 

```
              if (pubkeyInpsbt === pubkeyDerivedFromCosigner && psbt.inputHasPubkey(cc, child.publicKey)) {
                const keyPair = bitcoin.ECPair.fromPrivateKey(child.privateKey);
                try {
                  psbt.signInput(cc, keyPair);
```

versus

```
              if (psbt.inputHasPubkey(cc, child.publicKey)) {
                const keyPair = bitcoin.ECPair.fromPrivateKey(child.privateKey);
                try {
                  psbt.signInput(cc, keyPair);
```

the second one seems to be better

Comment (Overtorment) [reply class/wallets/multisig-hd-wallet.js:1031]: and ive just tried without try-catch and `psbt.signInput(cc, keyPair)` throws `Can not add duplicate data to array`

File: tests/unit/multisig-hd-wallet.test.js (hunk 6 above)
Comment (Overtorment) [reply tests/unit/multisig-hd-wallet.test.js:1073]: here it is

image

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4dxyvm49a0jedph7rvdgx2rfcc

[download apk](http://filestorage.bluewallet.io:1488/1609936209.apk)

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Comment by limpbrains** [comment]
@Overtorment I think this logic should be extended to wallet.createTransaction method

**Comment by Overtorment** [comment]
@limpbrains what logic? i dont remember whats this ticket about
