### PR TITLE
FIX: screen titles language

### LINKED ISSUE #2624: Text "Your wallet has been created" is not a multilanguage string.
Text "Your wallet has been created" is not a multilanguage string.

image

### PR DESCRIPTION
**Pull request by limpbrains**
Because screen navigationOptions were created on app start they had default English titles. I moved them to navigationStyle callback to be calculated dynamically. 

closes #2624

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/r0vm0w55chq919cmrug37cb6ar

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-screen-titles-1613377463.apk)

**Review by marcosrdz — APPROVED** [review]

File: screen/selftest.js [hunk 1]
```diff
@@ -65,7 +65,9 @@ export default class Selftest extends Component {
 
       if (typeof navigator !== 'undefined' && navigator.product === 'ReactNative') {
         const aezeed = new HDAezeedWallet();
-        aezeed.setSecret('abstract rhythm weird food attract treat mosquito sight royal actor surround ride strike remove guilt catch filter summer mushroom protect poverty cruel chaos pattern');
+        aezeed.setSecret(
```
Comment (Overtorment) [inline screen/selftest.js:68]: that should not be changed

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!
